# For Ruby

AllCops:
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Commonly used screens these days easily fit more than 80 characters.
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*_spec.rb'

# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 1000

Metrics/ModuleLength:
  Max: 1000

# For spec blocks, they are supposed to be long, so specs
# can be grouped. Only "it" blocks should be shorter
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'shared_examples_for']
  Exclude:
    - spec/support/factories/*
